name: Extract yml

on:
  push:
    paths:
      - "pipeline/extract.py"
      - "pipeline/test_extract.py"
  pull_request:
    paths:
      - "pipeline/extract.py"
      - "pipeline/test_extract.py"

jobs:
  test-extract:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - run: |
          python -m pip install --upgrade pip
          pip install -r pipeline/requirements.txt

      - name: Run extract tests (if present)
        run: |
          if [ -f pipeline/test_extract.py ]; then
            pytest -q pipeline/test_extract.py
          else
            echo "No test_extract.py found"
          fi

      - name: Lint extract only
        run: pylint pipeline/extract.py --fail-under=7
