name: Transform yml

on:
  push:
    paths:
      - "pipeline/transform.py"
      - "pipeline/tests/test_transform.py"
  pull_request:
    paths:
      - "pipeline/transform.py"
      - "pipeline/tests/test_transform.py"

jobs:
  test-transform:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - run: |
          python -m pip install --upgrade pip
          pip install -r pipeline/requirements.txt

      - name: Run transform tests
        run: pytest -q pipeline/test_transform.py

      - name: Lint transform only
        run: pylint pipeline/transform.py --fail-under=7
